spring.application.name=demo
#to expose all endpoints use *
management.endpoints.web.exposure.include=*

management.info.env.enabled=true

#to exclude desired endpoints
#management.endpoints.web.exposure.exclude=health



#comment added
info.app.name=MyCoolApp
info.app.desc=A good simple application.
info.app.version=1.0.0
